version: "3.8"

services:
    web:
      build: .
      env_file: .env
      ports:
        - "${WEB_PORT}:8000"

      networks:
        - quantum-mind-net
      restart: always
      command: sh -c "python3 manage.py migrate && python3 manage.py runserver 0.0.0.0:8000"
      depends_on:
        - postgresql_db

    postgresql_db:
      image: postgres:14-alpine
      restart: always
      env_file: .env
      ports:
        - "${DB_PORT}:5432"
      volumes:
        - postgresql_db_data:/var/lib/postgresql/data
      networks:
        - quantum-mind-net

volumes:
  postgresql_db_data:

networks:
    quantum-mind-net:
        external: true
