services:
    web:
      build: .
      env_file: .env
      ports:
        - "${WEB_PORT}:8000"

      networks:
        - quantum-mind-net
      restart: always
      volumes:
        - ./:/quantum_mind

      command: sh -c "python3 manage.py migrate && python3 manage.py runserver 0.0.0.0:8000"
      depends_on:
        - postgresql_db
        - ollama

    postgresql_db:
      image: postgres:14-alpine
      restart: always
      env_file: .env
      ports:
        - "${POSTGRES_PORT}:5432"
      volumes:
        - postgresql_db_data:/var/lib/postgresql/data
      networks:
        - quantum-mind-net

    ollama:
      image: ollama/ollama:latest
      restart: always
      ports:
        - "${OLLAMA_PORT}:11434"
      env_file: .env
      volumes:
        - ollama_data:/root/.ollama
      deploy:
        resources:
          reservations:
            devices:
              - driver: nvidia
                capabilities: [gpu]
      networks:
          - quantum-mind-net

volumes:
  postgresql_db_data:
  ollama_data:

networks:
    quantum-mind-net:
        internal: true
