# Generated by Django 5.0.6 on 2024-05-09 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Account",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=100, null=True, unique=True)),
                ("password", models.CharField(max_length=100)),
                ("user_name", models.CharField(max_length=100, unique=True)),
                ("is_superuser", models.BooleanField(default=False)),
            ],
        ),
        migrations.DeleteModel(
            name="Register",
        ),
    ]
