# Generated by Django 5.0.6 on 2024-05-17 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='App',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('version', models.CharField(max_length=100, null=True)),
                ('redirect_uri', models.TextField()),
                ('img_base64', models.TextField(null=True)),
            ],
        ),
    ]
