# Generated by Django 5.0.6 on 2024-06-13 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatsession',
            name='conversations',
            field=models.JSONField(default=list),
        ),
    ]
