# Generated by Django 5.0.6 on 2024-05-18 17:08

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0002_app'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='app',
            name='redirect_uri',
        ),
        migrations.AddField(
            model_name='account',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='account',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='app',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='app',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='app',
            name='url',
            field=models.TextField(default=django.utils.timezone.now, help_text='Redirect URI for the app'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='app',
            name='img_base64',
            field=models.TextField(blank=True, help_text='Base64 image of the app icon', null=True),
        ),
    ]
