# Generated by Django 5.0.6 on 2024-06-14 12:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0004_rename_system_instruction_custommodel_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='botfriend',
            name='conversations',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='botfriend',
            name='custom_model',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='public.custommodel'),
        ),
        migrations.AlterField(
            model_name='chatsession',
            name='conversations',
            field=models.JSONField(default=list),
        ),
    ]
