# Generated by Django 5.0.6 on 2024-05-20 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0005_alter_account_options_alter_account_managers_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatsession',
            name='chat_id',
        ),
    ]
