# Generated by Django 5.0.6 on 2024-06-14 12:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0005_alter_botfriend_conversations_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='botfriend',
            name='conversations',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='botfriend',
            name='custom_model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='public.custommodel'),
        ),
        migrations.AlterField(
            model_name='chatsession',
            name='conversations',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='custommodel',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
