# Generated by Django 5.0.6 on 2024-06-14 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0006_alter_botfriend_conversations_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='custommodel',
            old_name='description',
            new_name='more_info',
        ),
        migrations.AddField(
            model_name='custommodel',
            name='profession',
            field=models.CharField(default='student', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='botfriend',
            name='conversations',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='chatsession',
            name='conversations',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='custommodel',
            name='gender',
            field=models.CharField(default='neutral', max_length=10),
        ),
        migrations.AlterField(
            model_name='custommodel',
            name='language',
            field=models.CharField(choices=[('bn', 'Bengali'), ('en', 'English'), ('es', 'Spanish'), ('fr', 'French'), ('de', 'German'), ('it', 'Italian'), ('pt', 'Portuguese'), ('ru', 'Russian'), ('zh', 'Chinese'), ('ja', 'Japanese'), ('ko', 'Korean')], default='en', max_length=50),
        ),
        migrations.AlterField(
            model_name='custommodel',
            name='model_from',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='custommodel',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='custommodel',
            name='status',
            field=models.CharField(default='active', max_length=20),
        ),
    ]
