# Generated by Django 5.1.7 on 2025-03-23 09:40

import django.db.models.deletion
import public.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0008_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='url',
            old_name='image',
            new_name='img_base64',
        ),
        migrations.AlterField(
            model_name='url',
            name='long_url',
            field=models.URLField(unique=True),
        ),
        migrations.AlterField(
            model_name='url',
            name='short_url',
            field=models.CharField(default=public.models.generate_short_url, editable=False, max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='url',
            name='title',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='url',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
